openapi: 3.0.3
info:
  title: Aruba Cloud - Compute CloudServer API
  description: |
    REST API for managing CloudServer (Virtual Machine) resources in Aruba Cloud.
    This API allows you to create, read, update, and delete cloud server instances.
  version: 1.0.0
  contact:
    name: Aruba Cloud API Support
    url: https://www.arubacloud.com

servers:
  - url: https://api.arubacloud.com
    description: Production server

security:
  - BearerAuth: []

tags:
  - name: CloudServers
    description: Operations for managing CloudServer instances

paths:
  /projects/{projectId}/providers/Aruba.Compute/cloudservers:
    get:
      tags:
        - CloudServers
      summary: List CloudServers
      description: Retrieve a paginated list of CloudServer instances in a project
      operationId: listCloudServers
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/Filter'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Projection'
        - $ref: '#/components/parameters/Offset'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '200':
          description: Successfully retrieved CloudServer list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudServerList'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      tags:
        - CloudServers
      summary: Create CloudServer
      description: Create a new CloudServer instance
      operationId: createCloudServer
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CloudServerRequest'
      responses:
        '201':
          description: CloudServer successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudServerResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /projects/{projectId}/providers/Aruba.Compute/cloudservers/{cloudServerId}:
    get:
      tags:
        - CloudServers
      summary: Get CloudServer
      description: Retrieve details of a specific CloudServer instance
      operationId: getCloudServer
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/CloudServerIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '200':
          description: Successfully retrieved CloudServer details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudServerResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      tags:
        - CloudServers
      summary: Update CloudServer
      description: Update an existing CloudServer instance
      operationId: updateCloudServer
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/CloudServerIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CloudServerRequest'
      responses:
        '200':
          description: CloudServer successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudServerResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      tags:
        - CloudServers
      summary: Delete CloudServer
      description: Delete a CloudServer instance
      operationId: deleteCloudServer
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/CloudServerIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '204':
          description: CloudServer successfully deleted
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from the authentication endpoint

  parameters:
    ProjectIdPath:
      name: projectId
      in: path
      required: true
      description: Unique identifier of the project
      schema:
        type: string
        example: "my-project-id"

    CloudServerIdPath:
      name: cloudServerId
      in: path
      required: true
      description: Unique identifier of the CloudServer
      schema:
        type: string
        example: "my-cloudserver"

    Filter:
      name: filter
      in: query
      description: Filter expression for querying resources (OData-like syntax)
      schema:
        type: string
        example: "properties/zone eq 'ITBG-1'"

    Sort:
      name: sort
      in: query
      description: Sort expression for ordering results
      schema:
        type: string
        example: "metadata/name asc"

    Projection:
      name: projection
      in: query
      description: Fields to include in the response
      schema:
        type: string
        example: "metadata,properties/zone"

    Offset:
      name: offset
      in: query
      description: Number of items to skip (for pagination)
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0

    Limit:
      name: limit
      in: query
      description: Maximum number of items to return (for pagination)
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
        default: 20

    ApiVersion:
      name: api-version
      in: query
      description: API version to use for the request
      schema:
        type: string
        example: "2024-01-01"

  schemas:
    CloudServerRequest:
      type: object
      required:
        - metadata
        - properties
      properties:
        metadata:
          $ref: '#/components/schemas/RegionalResourceMetadataRequest'
        properties:
          $ref: '#/components/schemas/CloudServerPropertiesRequest'

    CloudServerResponse:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/ResourceMetadataResponse'
        properties:
          $ref: '#/components/schemas/CloudServerPropertiesResult'
        status:
          $ref: '#/components/schemas/ResourceStatus'

    CloudServerList:
      type: object
      properties:
        total:
          type: integer
          format: int64
          description: Total number of items
        self:
          type: string
          description: Self link to current page
        prev:
          type: string
          description: Link to previous page
        next:
          type: string
          description: Link to next page
        first:
          type: string
          description: Link to first page
        last:
          type: string
          description: Link to last page
        values:
          type: array
          items:
            $ref: '#/components/schemas/CloudServerResponse'

    CloudServerPropertiesRequest:
      type: object
      required:
        - dataCenter
        - vpc
        - elasticIp
        - bootVolume
        - keyPair
      properties:
        dataCenter:
          type: string
          description: Data center zone where the CloudServer will be deployed
          example: "ITBG-1"
        vpc:
          $ref: '#/components/schemas/ReferenceResource'
        vpcPreset:
          type: boolean
          description: Use VPC preset configuration
          default: false
        flavorName:
          type: string
          description: Name of the flavor (instance type)
          example: "CSO2A4"
        elasticIp:
          $ref: '#/components/schemas/ReferenceResource'
        bootVolume:
          $ref: '#/components/schemas/ReferenceResource'
        keyPair:
          $ref: '#/components/schemas/ReferenceResource'
        subnets:
          type: array
          items:
            $ref: '#/components/schemas/ReferenceResource'
        securityGroups:
          type: array
          items:
            $ref: '#/components/schemas/ReferenceResource'

    CloudServerPropertiesResult:
      type: object
      properties:
        linkedResources:
          type: array
          items:
            $ref: '#/components/schemas/LinkedResource'
        dataCenter:
          type: string
          description: Data center zone where the CloudServer is deployed
        vpc:
          $ref: '#/components/schemas/ReferenceResource'
        flavor:
          $ref: '#/components/schemas/CloudServerFlavorResponse'
        template:
          $ref: '#/components/schemas/ReferenceResource'
        bootVolume:
          $ref: '#/components/schemas/ReferenceResource'
        keyPair:
          $ref: '#/components/schemas/ReferenceResource'
        networkInterfaces:
          type: array
          items:
            $ref: '#/components/schemas/CloudServerNetworkInterfaceDetails'

    CloudServerFlavorResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the flavor
        name:
          type: string
          description: Name of the flavor
        category:
          type: string
          description: Category of the flavor
        cpu:
          type: integer
          format: int32
          description: Number of CPU cores
        ram:
          type: integer
          format: int32
          description: Amount of RAM in MB
        hd:
          type: integer
          format: int32
          description: Amount of disk space in GB

    CloudServerNetworkInterfaceDetails:
      type: object
      properties:
        subnet:
          type: string
          description: Subnet identifier
        macAddress:
          type: string
          description: MAC address of the network interface
        ips:
          type: array
          items:
            type: string
          description: IP addresses assigned to the interface

    RegionalResourceMetadataRequest:
      type: object
      required:
        - name
        - location
      properties:
        name:
          type: string
          description: Name of the resource
          example: "my-cloudserver"
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the resource
          example: ["production", "web-server"]
        location:
          $ref: '#/components/schemas/LocationRequest'

    LocationRequest:
      type: object
      required:
        - value
      properties:
        value:
          type: string
          description: Location identifier
          example: "ITBG-Bergamo"

    ResourceMetadataResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the resource
        uri:
          type: string
          description: URI of the resource
          example: "/projects/my-project/providers/Aruba.Compute/cloudservers/my-cloudserver"
        name:
          type: string
          description: Name of the resource
        location:
          $ref: '#/components/schemas/LocationResponse'
        project:
          $ref: '#/components/schemas/ProjectResponseMetadata'
        tags:
          type: array
          items:
            type: string
        category:
          $ref: '#/components/schemas/CategoryResponseMetadata'
        creationDate:
          type: string
          format: date-time
          description: Resource creation timestamp
        createdBy:
          type: string
          description: User who created the resource
        updateDate:
          type: string
          format: date-time
          description: Last update timestamp
        updatedBy:
          type: string
          description: User who last updated the resource
        version:
          type: string
          description: Resource version

    LocationResponse:
      type: object
      properties:
        code:
          type: string
          description: Location code
        country:
          type: string
          description: Country name
        region:
          type: string
          description: Region name
        city:
          type: string
          description: City name
        value:
          type: string
          description: Full location value

    ProjectResponseMetadata:
      type: object
      properties:
        id:
          type: string
          description: Project identifier

    CategoryResponseMetadata:
      type: object
      properties:
        name:
          type: string
          description: Category name
        provider:
          type: string
          description: Provider name
          example: "Aruba.Compute"
        typology:
          $ref: '#/components/schemas/TypologyResponseMetadata'

    TypologyResponseMetadata:
      type: object
      properties:
        id:
          type: string
          description: Typology identifier
        name:
          type: string
          description: Typology name

    ResourceStatus:
      type: object
      properties:
        state:
          type: string
          description: Current state of the resource
          enum:
            - Creating
            - Active
            - Updating
            - Deleting
            - Failed
            - Stopped
          example: "Active"
        creationDate:
          type: string
          format: date-time
          description: Status creation timestamp
        disableStatusInfo:
          $ref: '#/components/schemas/DisableStatusInfo'
        previousStatus:
          $ref: '#/components/schemas/PreviousStatus'
        failureReason:
          type: string
          description: Reason for failure (if state is Failed)

    DisableStatusInfo:
      type: object
      properties:
        isDisabled:
          type: boolean
          description: Whether the resource is disabled
        reasons:
          type: array
          items:
            type: string
          description: Reasons for disabling

    PreviousStatus:
      type: object
      properties:
        state:
          type: string
          description: Previous state of the resource
        creationDate:
          type: string
          format: date-time
          description: Previous status creation timestamp

    ReferenceResource:
      type: object
      required:
        - uri
      properties:
        uri:
          type: string
          description: URI reference to another resource
          example: "/projects/my-project/providers/Aruba.Network/vpcs/my-vpc"

    LinkedResource:
      type: object
      required:
        - uri
        - strictCorrelation
      properties:
        uri:
          type: string
          description: URI of the linked resource
        strictCorrelation:
          type: boolean
          description: Indicates if there's a strict correlation with this resource

    ErrorResponse:
      type: object
      properties:
        title:
          type: string
          description: Error title
          example: "Bad Request"
        status:
          type: integer
          description: HTTP status code
          example: 400
        detail:
          type: string
          description: Detailed error message
          example: "The request body is invalid"
        instance:
          type: string
          description: URI reference that identifies the specific occurrence of the problem
        type:
          type: string
          description: URI reference to the error type documentation

  responses:
    BadRequest:
      description: Bad Request - Invalid request parameters or body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: Unauthorized - Authentication is required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Forbidden:
      description: Forbidden - Insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Not Found - Resource does not exist
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Conflict:
      description: Conflict - Resource already exists or operation conflicts with current state
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
