openapi: 3.0.3
info:
  title: Aruba Cloud - Compute KeyPair API
  description: |
    REST API for managing SSH KeyPair resources in Aruba Cloud.
    This API allows you to create, read, update, and delete SSH key pairs for accessing cloud servers.
  version: 1.0.0
  contact:
    name: Aruba Cloud API Support
    url: https://www.arubacloud.com

servers:
  - url: https://api.arubacloud.com
    description: Production server

security:
  - BearerAuth: []

tags:
  - name: KeyPairs
    description: Operations for managing SSH KeyPairs

paths:
  /projects/{projectId}/providers/Aruba.Compute/keypairs:
    get:
      tags:
        - KeyPairs
      summary: List KeyPairs
      description: Retrieve a paginated list of SSH KeyPairs in a project
      operationId: listKeyPairs
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/Filter'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Projection'
        - $ref: '#/components/parameters/Offset'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '200':
          description: Successfully retrieved KeyPair list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyPairList'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      tags:
        - KeyPairs
      summary: Create KeyPair
      description: Create a new SSH KeyPair
      operationId: createKeyPair
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KeyPairRequest'
      responses:
        '201':
          description: KeyPair successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyPairResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /projects/{projectId}/providers/Aruba.Compute/keypairs/{keyPairId}:
    get:
      tags:
        - KeyPairs
      summary: Get KeyPair
      description: Retrieve details of a specific SSH KeyPair
      operationId: getKeyPair
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/KeyPairIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '200':
          description: Successfully retrieved KeyPair details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyPairResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      tags:
        - KeyPairs
      summary: Update KeyPair
      description: Update an existing SSH KeyPair
      operationId: updateKeyPair
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/KeyPairIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KeyPairRequest'
      responses:
        '200':
          description: KeyPair successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyPairResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      tags:
        - KeyPairs
      summary: Delete KeyPair
      description: Delete an SSH KeyPair
      operationId: deleteKeyPair
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/KeyPairIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '204':
          description: KeyPair successfully deleted
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from the authentication endpoint

  parameters:
    ProjectIdPath:
      name: projectId
      in: path
      required: true
      description: Unique identifier of the project
      schema:
        type: string
        example: "my-project-id"

    KeyPairIdPath:
      name: keyPairId
      in: path
      required: true
      description: Unique identifier of the KeyPair
      schema:
        type: string
        example: "my-keypair"

    Filter:
      name: filter
      in: query
      description: Filter expression for querying resources (OData-like syntax)
      schema:
        type: string
        example: "properties/value contains 'ssh-rsa'"

    Sort:
      name: sort
      in: query
      description: Sort expression for ordering results
      schema:
        type: string
        example: "metadata/name asc"

    Projection:
      name: projection
      in: query
      description: Fields to include in the response
      schema:
        type: string
        example: "metadata,properties/value"

    Offset:
      name: offset
      in: query
      description: Number of items to skip (for pagination)
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0

    Limit:
      name: limit
      in: query
      description: Maximum number of items to return (for pagination)
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
        default: 20

    ApiVersion:
      name: api-version
      in: query
      description: API version to use for the request
      schema:
        type: string
        example: "2024-01-01"

  schemas:
    # KeyPair Schemas
    KeyPairRequest:
      type: object
      required:
        - metadata
        - properties
      properties:
        metadata:
          $ref: '#/components/schemas/RegionalResourceMetadataRequest'
        properties:
          $ref: '#/components/schemas/KeyPairPropertiesRequest'

    KeyPairPropertiesRequest:
      type: object
      required:
        - value
      properties:
        value:
          type: string
          description: SSH public key value
          example: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC..."

    KeyPairResponse:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/ResourceMetadataResponse'
        properties:
          $ref: '#/components/schemas/KeyPairPropertiesResult'
        status:
          $ref: '#/components/schemas/ResourceStatus'

    KeyPairPropertiesResult:
      type: object
      properties:
        linkedResources:
          type: array
          items:
            $ref: '#/components/schemas/LinkedResource'
          description: List of CloudServers using this KeyPair
        value:
          type: string
          description: SSH public key value

    KeyPairList:
      type: object
      properties:
        total:
          type: integer
          format: int64
          description: Total number of items
        self:
          type: string
          description: Self link to current page
        prev:
          type: string
          description: Link to previous page
        next:
          type: string
          description: Link to next page
        first:
          type: string
          description: Link to first page
        last:
          type: string
          description: Link to last page
        values:
          type: array
          items:
            $ref: '#/components/schemas/KeyPairResponse'

    # Common Schemas
    RegionalResourceMetadataRequest:
      type: object
      required:
        - name
        - location
      properties:
        name:
          type: string
          description: Name of the resource
          example: "my-keypair"
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the resource
          example: ["production", "ssh-access"]
        location:
          $ref: '#/components/schemas/LocationRequest'

    LocationRequest:
      type: object
      required:
        - value
      properties:
        value:
          type: string
          description: Location identifier
          example: "ITBG-Bergamo"

    ResourceMetadataResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the resource
        uri:
          type: string
          description: URI of the resource
          example: "/projects/my-project/providers/Aruba.Compute/keypairs/my-keypair"
        name:
          type: string
          description: Name of the resource
        location:
          $ref: '#/components/schemas/LocationResponse'
        project:
          $ref: '#/components/schemas/ProjectResponseMetadata'
        tags:
          type: array
          items:
            type: string
        category:
          $ref: '#/components/schemas/CategoryResponseMetadata'
        creationDate:
          type: string
          format: date-time
          description: Resource creation timestamp
        createdBy:
          type: string
          description: User who created the resource
        updateDate:
          type: string
          format: date-time
          description: Last update timestamp
        updatedBy:
          type: string
          description: User who last updated the resource
        version:
          type: string
          description: Resource version

    LocationResponse:
      type: object
      properties:
        code:
          type: string
          description: Location code
        country:
          type: string
          description: Country name
        region:
          type: string
          description: Region name
        city:
          type: string
          description: City name
        value:
          type: string
          description: Full location value

    ProjectResponseMetadata:
      type: object
      properties:
        id:
          type: string
          description: Project identifier

    CategoryResponseMetadata:
      type: object
      properties:
        name:
          type: string
          description: Category name
        provider:
          type: string
          description: Provider name
          example: "Aruba.Compute"
        typology:
          $ref: '#/components/schemas/TypologyResponseMetadata'

    TypologyResponseMetadata:
      type: object
      properties:
        id:
          type: string
          description: Typology identifier
        name:
          type: string
          description: Typology name

    ResourceStatus:
      type: object
      properties:
        state:
          type: string
          description: Current state of the resource
          enum:
            - Creating
            - Active
            - Updating
            - Deleting
            - Failed
          example: "Active"
        creationDate:
          type: string
          format: date-time
          description: Status creation timestamp
        disableStatusInfo:
          $ref: '#/components/schemas/DisableStatusInfo'
        previousStatus:
          $ref: '#/components/schemas/PreviousStatus'
        failureReason:
          type: string
          description: Reason for failure (if state is Failed)

    DisableStatusInfo:
      type: object
      properties:
        isDisabled:
          type: boolean
          description: Whether the resource is disabled
        reasons:
          type: array
          items:
            type: string
          description: Reasons for disabling

    PreviousStatus:
      type: object
      properties:
        state:
          type: string
          description: Previous state of the resource
        creationDate:
          type: string
          format: date-time
          description: Previous status creation timestamp

    LinkedResource:
      type: object
      required:
        - uri
        - strictCorrelation
      properties:
        uri:
          type: string
          description: URI of the linked resource
        strictCorrelation:
          type: boolean
          description: Indicates if there's a strict correlation with this resource

    ErrorResponse:
      type: object
      properties:
        title:
          type: string
          description: Error title
          example: "Bad Request"
        status:
          type: integer
          description: HTTP status code
          example: 400
        detail:
          type: string
          description: Detailed error message
          example: "The request body is invalid"
        instance:
          type: string
          description: URI reference that identifies the specific occurrence of the problem
        type:
          type: string
          description: URI reference to the error type documentation

  responses:
    BadRequest:
      description: Bad Request - Invalid request parameters or body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: Unauthorized - Authentication is required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Forbidden:
      description: Forbidden - Insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Not Found - Resource does not exist
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Conflict:
      description: Conflict - Resource already exists or operation conflicts with current state
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
