openapi: 3.0.3
info:
  title: Aruba Cloud - Elastic IP API
  description: |
    REST API for managing Elastic IP resources in Aruba Cloud.
    Elastic IPs provide static public IP addresses that can be associated with cloud resources.
  version: 1.0.0
  contact:
    name: Aruba Cloud API Support
    url: https://www.arubacloud.com

servers:
  - url: https://api.arubacloud.com
    description: Production server

security:
  - BearerAuth: []

tags:
  - name: ElasticIPs
    description: Elastic IP operations

paths:
  /projects/{projectId}/providers/Aruba.Network/elasticIps:
    get:
      tags: [ElasticIPs]
      summary: List Elastic IPs
      operationId: listElasticIPs
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/Filter'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Offset'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '200':
          description: Elastic IP list retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElasticIPList'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      tags: [ElasticIPs]
      summary: Create Elastic IP
      operationId: createElasticIP
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElasticIPRequest'
      responses:
        '201':
          description: Elastic IP created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElasticIPResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /projects/{projectId}/providers/Aruba.Network/elasticIps/{elasticIpId}:
    get:
      tags: [ElasticIPs]
      summary: Get Elastic IP
      operationId: getElasticIP
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/ElasticIpIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '200':
          description: Elastic IP details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElasticIPResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      tags: [ElasticIPs]
      summary: Update Elastic IP
      operationId: updateElasticIP
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/ElasticIpIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElasticIPRequest'
      responses:
        '200':
          description: Elastic IP updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElasticIPResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      tags: [ElasticIPs]
      summary: Delete Elastic IP
      operationId: deleteElasticIP
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/ElasticIpIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '204':
          description: Elastic IP deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    ProjectIdPath:
      name: projectId
      in: path
      required: true
      description: The unique identifier of the project
      schema:
        type: string

    ElasticIpIdPath:
      name: elasticIpId
      in: path
      required: true
      description: The unique identifier of the elastic IP
      schema:
        type: string

    Filter:
      name: filter
      in: query
      description: Filter expression for results
      schema:
        type: string

    Sort:
      name: sort
      in: query
      description: Sort expression for results
      schema:
        type: string

    Offset:
      name: offset
      in: query
      description: Number of items to skip
      schema:
        type: integer
        format: int32
        default: 0

    Limit:
      name: limit
      in: query
      description: Maximum number of items to return
      schema:
        type: integer
        format: int32
        default: 50

    ApiVersion:
      name: api-version
      in: query
      description: API version
      schema:
        type: string

  schemas:
    ElasticIPRequest:
      type: object
      required:
        - metadata
        - properties
      properties:
        metadata:
          $ref: '#/components/schemas/RegionalResourceMetadataRequest'
        properties:
          type: object
          required:
            - billingPlan
          properties:
            billingPlan:
              type: object
              required:
                - billingPeriod
              properties:
                billingPeriod:
                  type: string
                  description: Billing period for the elastic IP
                  enum: [Hourly, Monthly, Yearly]
                  example: "Monthly"

    ElasticIPResponse:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/ResourceMetadataResponse'
        properties:
          type: object
          properties:
            ipAddress:
              type: string
              description: The allocated IP address
              example: "203.0.113.42"
            billingPlan:
              type: object
              properties:
                billingPeriod:
                  type: string
                  description: Billing period for the elastic IP
        status:
          $ref: '#/components/schemas/ResourceStatus'

    ElasticIPList:
      allOf:
        - $ref: '#/components/schemas/ListResponse'
        - type: object
          properties:
            values:
              type: array
              items:
                $ref: '#/components/schemas/ElasticIPResponse'

    RegionalResourceMetadataRequest:
      type: object
      required:
        - name
        - location
      properties:
        name:
          type: string
          description: Name of the resource
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the resource
        location:
          type: object
          required:
            - value
          properties:
            value:
              type: string
              description: Location identifier

    ResourceMetadataResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the resource
        uri:
          type: string
          description: URI of the resource
        name:
          type: string
          description: Name of the resource
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the resource
        creationDate:
          type: string
          format: date-time
          description: Resource creation timestamp

    ResourceStatus:
      type: object
      properties:
        state:
          type: string
          enum: [Creating, Active, Updating, Deleting, Failed]
          description: Current state of the resource
        creationDate:
          type: string
          format: date-time
          description: Status creation timestamp
        failureReason:
          type: string
          description: Reason for failure if state is Failed

    ListResponse:
      type: object
      properties:
        total:
          type: integer
          format: int64
          description: Total number of items available
        self:
          type: string
          description: Link to current page
        next:
          type: string
          description: Link to next page
        prev:
          type: string
          description: Link to previous page

    ErrorResponse:
      type: object
      properties:
        title:
          type: string
          description: Error title
        status:
          type: integer
          description: HTTP status code
        detail:
          type: string
          description: Detailed error message

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
