openapi: 3.0.3
info:
  title: Aruba Cloud - Subnet API
  description: |
    REST API for managing Subnet resources in Aruba Cloud VPCs.
    Subnets provide network segmentation within Virtual Private Clouds.
  version: 1.0.0
  contact:
    name: Aruba Cloud API Support
    url: https://www.arubacloud.com

servers:
  - url: https://api.arubacloud.com
    description: Production server

security:
  - BearerAuth: []

tags:
  - name: Subnets
    description: Subnet operations

paths:
  /projects/{projectId}/providers/Aruba.Network/vpcs/{vpcId}/subnets:
    get:
      tags: [Subnets]
      summary: List Subnets
      operationId: listSubnets
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/VpcIdPath'
        - $ref: '#/components/parameters/Filter'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Offset'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '200':
          description: Subnet list retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubnetList'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      tags: [Subnets]
      summary: Create Subnet
      operationId: createSubnet
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/VpcIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubnetRequest'
      responses:
        '201':
          description: Subnet created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubnetResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /projects/{projectId}/providers/Aruba.Network/vpcs/{vpcId}/subnets/{subnetId}:
    get:
      tags: [Subnets]
      summary: Get Subnet
      operationId: getSubnet
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/VpcIdPath'
        - $ref: '#/components/parameters/SubnetIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '200':
          description: Subnet details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubnetResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      tags: [Subnets]
      summary: Update Subnet
      operationId: updateSubnet
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/VpcIdPath'
        - $ref: '#/components/parameters/SubnetIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubnetRequest'
      responses:
        '200':
          description: Subnet updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubnetResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      tags: [Subnets]
      summary: Delete Subnet
      operationId: deleteSubnet
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/VpcIdPath'
        - $ref: '#/components/parameters/SubnetIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '204':
          description: Subnet deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    ProjectIdPath:
      name: projectId
      in: path
      required: true
      description: The unique identifier of the project
      schema:
        type: string

    VpcIdPath:
      name: vpcId
      in: path
      required: true
      description: The unique identifier of the VPC
      schema:
        type: string

    SubnetIdPath:
      name: subnetId
      in: path
      required: true
      description: The unique identifier of the subnet
      schema:
        type: string

    Filter:
      name: filter
      in: query
      description: Filter expression for results
      schema:
        type: string

    Sort:
      name: sort
      in: query
      description: Sort expression for results
      schema:
        type: string

    Offset:
      name: offset
      in: query
      description: Number of items to skip
      schema:
        type: integer
        format: int32
        default: 0

    Limit:
      name: limit
      in: query
      description: Maximum number of items to return
      schema:
        type: integer
        format: int32
        default: 50

    ApiVersion:
      name: api-version
      in: query
      description: API version
      schema:
        type: string

  schemas:
    SubnetRequest:
      type: object
      required:
        - metadata
        - properties
      properties:
        metadata:
          $ref: '#/components/schemas/RegionalResourceMetadataRequest'
        properties:
          type: object
          required:
            - type
            - network
          properties:
            type:
              type: string
              enum: [Basic, Advanced]
              description: Type of subnet (Basic or Advanced)
            default:
              type: boolean
              description: Whether this is the default subnet
              default: false
            network:
              type: object
              required:
                - address
              properties:
                address:
                  type: string
                  description: CIDR notation for subnet address (e.g., 10.0.1.0/24)
            dhcp:
              type: object
              properties:
                enabled:
                  type: boolean
                  description: Whether DHCP is enabled for this subnet
                  default: true

    SubnetResponse:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/ResourceMetadataResponse'
        properties:
          type: object
          properties:
            type:
              type: string
              description: Type of subnet
            default:
              type: boolean
              description: Whether this is the default subnet
            network:
              type: object
              properties:
                address:
                  type: string
                  description: CIDR notation for subnet address
            dhcp:
              type: object
              properties:
                enabled:
                  type: boolean
                  description: Whether DHCP is enabled
        status:
          $ref: '#/components/schemas/ResourceStatus'

    SubnetList:
      allOf:
        - $ref: '#/components/schemas/ListResponse'
        - type: object
          properties:
            values:
              type: array
              items:
                $ref: '#/components/schemas/SubnetResponse'

    RegionalResourceMetadataRequest:
      type: object
      required:
        - name
        - location
      properties:
        name:
          type: string
          description: Name of the resource
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the resource
        location:
          type: object
          required:
            - value
          properties:
            value:
              type: string
              description: Location identifier

    ResourceMetadataResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the resource
        uri:
          type: string
          description: URI of the resource
        name:
          type: string
          description: Name of the resource
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the resource
        creationDate:
          type: string
          format: date-time
          description: Resource creation timestamp

    ResourceStatus:
      type: object
      properties:
        state:
          type: string
          enum: [Creating, Active, Updating, Deleting, Failed]
          description: Current state of the resource
        creationDate:
          type: string
          format: date-time
          description: Status creation timestamp
        failureReason:
          type: string
          description: Reason for failure if state is Failed

    ListResponse:
      type: object
      properties:
        total:
          type: integer
          format: int64
          description: Total number of items available
        self:
          type: string
          description: Link to current page
        next:
          type: string
          description: Link to next page
        prev:
          type: string
          description: Link to previous page

    ErrorResponse:
      type: object
      properties:
        title:
          type: string
          description: Error title
        status:
          type: integer
          description: HTTP status code
        detail:
          type: string
          description: Detailed error message

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
