openapi: 3.0.3
info:
  title: Aruba Cloud - VPN Tunnel API
  description: |
    REST API for managing VPN Tunnel resources in Aruba Cloud.
    VPN Tunnels provide secure connections between cloud resources and external networks.
  version: 1.0.0
  contact:
    name: Aruba Cloud API Support
    url: https://www.arubacloud.com

servers:
  - url: https://api.arubacloud.com
    description: Production server

security:
  - BearerAuth: []

tags:
  - name: VPNTunnels
    description: VPN tunnel operations

paths:
  /projects/{projectId}/providers/Aruba.Network/vpntunnels:
    get:
      tags: [VPNTunnels]
      summary: List VPN Tunnels
      operationId: listVPNTunnels
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/Filter'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Offset'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '200':
          description: VPN tunnel list retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VPNTunnelList'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      tags: [VPNTunnels]
      summary: Create VPN Tunnel
      operationId: createVPNTunnel
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VPNTunnelRequest'
      responses:
        '201':
          description: VPN tunnel created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VPNTunnelResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /projects/{projectId}/providers/Aruba.Network/vpntunnels/{vpnTunnelId}:
    get:
      tags: [VPNTunnels]
      summary: Get VPN Tunnel
      operationId: getVPNTunnel
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/VpnTunnelIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '200':
          description: VPN tunnel details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VPNTunnelResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      tags: [VPNTunnels]
      summary: Update VPN Tunnel
      operationId: updateVPNTunnel
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/VpnTunnelIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VPNTunnelRequest'
      responses:
        '200':
          description: VPN tunnel updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VPNTunnelResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      tags: [VPNTunnels]
      summary: Delete VPN Tunnel
      operationId: deleteVPNTunnel
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/VpnTunnelIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '204':
          description: VPN tunnel deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    ProjectIdPath:
      name: projectId
      in: path
      required: true
      description: The unique identifier of the project
      schema:
        type: string

    VpnTunnelIdPath:
      name: vpnTunnelId
      in: path
      required: true
      description: The unique identifier of the VPN tunnel
      schema:
        type: string

    Filter:
      name: filter
      in: query
      description: Filter expression for results
      schema:
        type: string

    Sort:
      name: sort
      in: query
      description: Sort expression for results
      schema:
        type: string

    Offset:
      name: offset
      in: query
      description: Number of items to skip
      schema:
        type: integer
        format: int32
        default: 0

    Limit:
      name: limit
      in: query
      description: Maximum number of items to return
      schema:
        type: integer
        format: int32
        default: 50

    ApiVersion:
      name: api-version
      in: query
      description: API version
      schema:
        type: string

  schemas:
    VPNTunnelRequest:
      type: object
      required:
        - metadata
        - properties
      properties:
        metadata:
          $ref: '#/components/schemas/ResourceMetadataRequest'
        properties:
          type: object
          description: VPN tunnel configuration properties

    VPNTunnelResponse:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/ResourceMetadataResponse'
        properties:
          type: object
          description: VPN tunnel properties
        status:
          $ref: '#/components/schemas/ResourceStatus'

    VPNTunnelList:
      allOf:
        - $ref: '#/components/schemas/ListResponse'
        - type: object
          properties:
            values:
              type: array
              items:
                $ref: '#/components/schemas/VPNTunnelResponse'

    ResourceMetadataRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the resource
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the resource

    ResourceMetadataResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the resource
        uri:
          type: string
          description: URI of the resource
        name:
          type: string
          description: Name of the resource
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the resource
        creationDate:
          type: string
          format: date-time
          description: Resource creation timestamp

    ResourceStatus:
      type: object
      properties:
        state:
          type: string
          enum: [Creating, Active, Updating, Deleting, Failed]
          description: Current state of the resource
        creationDate:
          type: string
          format: date-time
          description: Status creation timestamp
        failureReason:
          type: string
          description: Reason for failure if state is Failed

    ListResponse:
      type: object
      properties:
        total:
          type: integer
          format: int64
          description: Total number of items available
        self:
          type: string
          description: Link to current page
        next:
          type: string
          description: Link to next page
        prev:
          type: string
          description: Link to previous page

    ErrorResponse:
      type: object
      properties:
        title:
          type: string
          description: Error title
        status:
          type: integer
          description: HTTP status code
        detail:
          type: string
          description: Detailed error message

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
