openapi: 3.0.3
info:
  title: Aruba Cloud - Block Storage API
  description: |
    REST API for managing Block Storage volumes in Aruba Cloud.
    Block storage volumes provide persistent storage that can be attached to cloud servers.
  version: 1.0.0
  contact:
    name: Aruba Cloud API Support
    url: https://www.arubacloud.com

servers:
  - url: https://api.arubacloud.com
    description: Production server

security:
  - BearerAuth: []

tags:
  - name: BlockStorage
    description: Block storage volume operations

paths:
  /projects/{projectId}/providers/Aruba.Storage/blockstorages:
    get:
      tags: [BlockStorage]
      summary: List Block Storage Volumes
      operationId: listBlockStorages
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/Filter'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Offset'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '200':
          description: Successfully retrieved block storage list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockStorageList'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      tags: [BlockStorage]
      summary: Create Block Storage Volume
      operationId: createBlockStorage
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlockStorageRequest'
      responses:
        '201':
          description: Block storage successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockStorageResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /projects/{projectId}/providers/Aruba.Storage/blockstorages/{volumeId}:
    get:
      tags: [BlockStorage]
      summary: Get Block Storage Volume
      operationId: getBlockStorage
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/VolumeIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '200':
          description: Successfully retrieved block storage details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockStorageResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      tags: [BlockStorage]
      summary: Update Block Storage Volume
      operationId: updateBlockStorage
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/VolumeIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlockStorageRequest'
      responses:
        '200':
          description: Block storage successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockStorageResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      tags: [BlockStorage]
      summary: Delete Block Storage Volume
      operationId: deleteBlockStorage
      parameters:
        - $ref: '#/components/parameters/ProjectIdPath'
        - $ref: '#/components/parameters/VolumeIdPath'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '204':
          description: Block storage successfully deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    ProjectIdPath:
      name: projectId
      in: path
      required: true
      description: The unique identifier of the project
      schema:
        type: string

    VolumeIdPath:
      name: volumeId
      in: path
      required: true
      description: The unique identifier of the block storage volume
      schema:
        type: string

    Filter:
      name: filter
      in: query
      description: Filter expression for results
      schema:
        type: string

    Sort:
      name: sort
      in: query
      description: Sort expression for results
      schema:
        type: string

    Offset:
      name: offset
      in: query
      description: Number of items to skip
      schema:
        type: integer
        format: int32
        default: 0

    Limit:
      name: limit
      in: query
      description: Maximum number of items to return
      schema:
        type: integer
        format: int32
        default: 50

    ApiVersion:
      name: api-version
      in: query
      description: API version
      schema:
        type: string

  schemas:
    BlockStorageRequest:
      type: object
      required:
        - metadata
        - properties
      properties:
        metadata:
          $ref: '#/components/schemas/RegionalResourceMetadataRequest'
        properties:
          type: object
          required:
            - sizeGB
            - type
            - zone
            - billingPeriod
          properties:
            sizeGB:
              type: integer
              format: int32
              description: Size of the volume in gigabytes
              minimum: 10
              maximum: 16384
            type:
              type: string
              enum: [Standard, Premium, Ultra]
              description: Performance tier of the block storage
            zone:
              type: string
              description: Availability zone for the volume
            billingPeriod:
              type: string
              description: Billing period for the volume
            bootable:
              type: boolean
              description: Whether the volume is bootable
              default: false
            image:
              type: string
              description: Optional OS image to initialize the volume with

    BlockStorageResponse:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/ResourceMetadataResponse'
        properties:
          type: object
          properties:
            sizeGB:
              type: integer
              format: int32
              description: Size of the volume in gigabytes
            type:
              type: string
              description: Performance tier of the block storage
            zone:
              type: string
              description: Availability zone for the volume
            billingPeriod:
              type: string
              description: Billing period for the volume
            bootable:
              type: boolean
              description: Whether the volume is bootable
        status:
          $ref: '#/components/schemas/ResourceStatus'

    BlockStorageList:
      allOf:
        - $ref: '#/components/schemas/ListResponse'
        - type: object
          properties:
            values:
              type: array
              items:
                $ref: '#/components/schemas/BlockStorageResponse'

    RegionalResourceMetadataRequest:
      type: object
      required:
        - name
        - location
      properties:
        name:
          type: string
          description: Name of the resource
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the resource
        location:
          type: object
          required:
            - value
          properties:
            value:
              type: string
              description: Location identifier

    ResourceMetadataResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the resource
        uri:
          type: string
          description: URI of the resource
        name:
          type: string
          description: Name of the resource
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the resource
        location:
          type: object
          properties:
            value:
              type: string
              description: Location identifier
            region:
              type: string
              description: Region name
            city:
              type: string
              description: City name
        creationDate:
          type: string
          format: date-time
          description: Resource creation timestamp
        updateDate:
          type: string
          format: date-time
          description: Resource last update timestamp

    ResourceStatus:
      type: object
      properties:
        state:
          type: string
          enum: [Creating, Active, Updating, Deleting, Failed]
          description: Current state of the resource
        creationDate:
          type: string
          format: date-time
          description: Status creation timestamp
        failureReason:
          type: string
          description: Reason for failure if state is Failed

    ListResponse:
      type: object
      properties:
        total:
          type: integer
          format: int64
          description: Total number of items available
        self:
          type: string
          description: Link to current page
        prev:
          type: string
          description: Link to previous page
        next:
          type: string
          description: Link to next page
        first:
          type: string
          description: Link to first page
        last:
          type: string
          description: Link to last page

    ErrorResponse:
      type: object
      properties:
        title:
          type: string
          description: Error title
        status:
          type: integer
          description: HTTP status code
        detail:
          type: string
          description: Detailed error message

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
